### ISSUE TITLE
Further questions about "Spectrum Synthesis"

### ISSUE THREAD

**Issue by Liu-Zhilin** [XPengZhao/NeRF2#10]
Thanks for sharing the code and datasets!Your work is truly impressive！
Regarding the "Spectrum Synthesis" experiment detailed in your paper, I have a few inquiries:
1.As depicted in your paper and code, NeRF2 is capable of predicting the reception of RF signals given the transmitter's position, as illustrated in Figure 2. I am particularly intrigued by the role of the maps of the scene in this prediction process.  Specifically, I am curious to know whether the scene maps actively contribute to the prediction, or we can just treat the scene as a black box and predict the spectrum directly by placing tags at random positions to capture sufficient spatial spectrum datasets.
2.Furthermore, I am contemplating the robustness of the model in scenarios where minor alterations occur within the original setting. For instance, the introduction of a table or an increase in the number of people present. I am curious to know whether such subtle changes would have a significant impact on the accuracy of the spectrum prediction. Understanding the model's sensitivity to environmental dynamics is crucial for assessing its reliability in real-world applications, where conditions are often unpredictable and subject to change.
Thank you for your reply!

**Comment by XPengZhao** [comment]
Thank you for your constructive inquiries regarding our work.

1. NeRF2 and similar works use implicit representations of environments. If you wish to integrate scene maps, consider adopting explicit representations such as neural signed distance functions, neural voxel grids, or 3D Gaussian splatting. These methods initialize with a scene map and can provide a more structured approach to environmental modeling. Additionally, differentiable ray tracing, such as NV Sionna, may also be explored to enhance scene representation in the prediction process.

2. The impact of such changes largely depends on specific properties of the RF signal, particularly the wavelength. Signals above 6 GHz, for instance, are likely to be significantly affected by minor environmental variations. To address this, using an explicit modeling approach that allows for dynamic adjustments in response to new environmental conditions could prove beneficial.

**Comment by Liu-Zhilin** [comment]
Thank you for your answers!

**Comment by Liu-Zhilin** [comment]
Could you please suggest some papers or research focusing on explicit modeling methodologies? I'd like to broaden my understanding in this domain. Thank you for your recommendation!

**Comment by XPengZhao** [comment]
Here are some references:
[1] 3D Gaussian Splatting for Real-Time Radiance Field Rendering
[2] Neuralangelo: High-Fidelity Neural Surface Reconstruction
[3] Neural Sparse Voxel Fields
[4] WINERT: TOWARDS NEURAL RAY TRACING FORWIRELESS CHANNEL MODELLING AND DIFFEREN-TIABLE SIMULATIONS
[5] Sionna: An Open-Source Library for Next-Generation Physical Layer Research
[6] RF-Diffusion: Radio Signal Generation via Time-Frequency Diffusion

**Comment by Liu-Zhilin** [comment]
Thank you!
