### ISSUE TITLE
getting voxel origin

### ISSUE THREAD

**Issue by Forge-Lee** [XPengZhao/NeRF2#2]
Hi! I'm very impressed by your work, it's amazing that in the given demo your performance is so closed to the ground truth.

I'm a little bit confused that how you get the origin of the voxel, which is one of the input of the network (if I did not misunderstand). Is the method in the dataloader that generating sample ray origin implementing this part?

I'd appreciate it if you can reply.

**Comment by Forge-Lee** [comment]
Then what about the coordinate of the voxel? I understand it as after getting the origin and the directions, we do "ray-tracing" and see where the ray interacts with the environment. Then we find a series of voxels along the ray from the interaction point and we have the coordinates. Is such understanding correct?

**Comment by XPengZhao** [comment]
In practice, we first establish a global coordinate system using an optical tracking system or SLAM. This enables us to pinpoint the coordinates of the antenna array, which serves as the origin of the ray. Next, we perform "ray tracing" to determine where the ray interacts with the environment.

The coordinate of a specific voxel along the ray from the interaction point can then be calculated using the formula $p_{voxel} = o + td$, where 'o' represents the origin, 't' is the distance along the ray, and 'd' is the direction of the ray.

<img src=https://github.com/XPengZhao/NeRF2/assets/30794695/3a9eaced-e580-4803-9728-8604e77d00cd width=50%>

**Comment by ankuraditya98** [comment]
Hi,

Just a Follow-up question.

From the code it looks like for predicting spectrum you have set the number of voxel samples/ray to 64(n_samples) . Resulting in pts tensor of shape [n_rays, n_voxels, 3]. 

I am a bit confused on how have you decided the number of samples - Is it the Hyperparmeter which you have tuned? Or as mentioned in the paper you have taken voxel size of 1/8 of wavelength.
