### ISSUE TITLE
Size of checkpoint for pretrained RFID model doesn't match model size

### ISSUE THREAD

**Issue by viktormuller** [XPengZhao/NeRF2#4]
I am trying to reproduce the results for inference using pretrained RFID model. 

I have downloaded the checkpoint file from the [One Drive](https://connectpolyu-my.sharepoint.com/personal/20032132r_connect_polyu_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2F20032132r%5Fconnect%5Fpolyu%5Fhk%2FDocuments%2FNeRF2%2DDataset%2FRFID). 

I tried to run it with `python nerf2_runner.py --mode test --config configs/rfid-spectrum.yml --dataset_type rfid`

However it fails with:

```
RuntimeError: Error(s) in loading state_dict for NeRF2:
        size mismatch for attenuation_linears.0.weight: copying a param with shape torch.Size([256, 63]) from checkpoint, the shape in current model is torch.Size([256, 60]).
        size mismatch for attenuation_linears.5.weight: copying a param with shape torch.Size([256, 319]) from checkpoint, the shape in current model is torch.Size([256, 316]).
        size mismatch for signal_linears.0.weight: copying a param with shape torch.Size([256, 382]) from checkpoint, the shape in current model is torch.Size([256, 376]).
```

I believe that the model size is correct based on the paper but for some reason the checkpoint contains 3 extra columns whenever a 3D position vector is embedded. 

I am working on a windows 11, so I am also wondering if new line encoding plays a role in the serialization / deserialization of the checkpoint.

Note that I have omitted the --gpu 0 switch because I haven't done a CUDA setup for this initial inference test. I removed the references to the GPU from the nerf2 runner and configured to run on CPU. 

Any help or direction is much appreciated.

**Comment by Jcq242818** [comment]
I met the same problem, so I had to retrain the model using the dataset set provided by the authors on GPU. Then, there's no problem with the test process.

**Comment by XPengZhao** [comment]
For debugging purposes, I set `include_input` to `False` (refer to line 80 in model.py), which resulted in a bug preventing the loading of checkpoints. In the updated version, I have corrected this by setting `include_input: True`.

**Comment by viktormuller** [comment]
Forgot to close with the previous comment. Closing now.
