### ISSUE TITLE
Can't load s23-ckpts.tar

### ISSUE THREAD

**Issue by chrisVat** [XPengZhao/NeRF2#6]
Upon extracting s23-ckpts.tar, it becomes a folder with a number containing data.pkl, data/ and version. 
How do I load this as a model? Attempting to load with pkl natively fails, both when using the standard pkl.load function and writing some custom persistent loading methods.

**Comment by chrisVat** [comment]
Same applies for all other ckpts tar files. Unclear how to get the model from these files.

**Comment by XPengZhao** [comment]
You do not need to extract `s23-ckpts.tar`. Just directly place the pretrained model in the `ckpts` folder.

**Comment by chrisVat** [comment]
thanks!
