### ISSUE TITLE
Inquiry on extracting csidata.npy from raw-csi-data

### ISSUE THREAD

**Issue by Spinning-Fish** [XPengZhao/NeRF2#7]
Thanks for sharing the codes. Your team's project is quite appealing! 
I'm trying to train the CSI prediction model but feel a bit confused about how to extract `csidata.npy` from [Raw-CSI-Data](https://connectpolyu-my.sharepoint.com/personal/20032132r_connect_polyu_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2F20032132r%5Fconnect%5Fpolyu%5Fhk%2FDocuments%2FNeRF2%2DDataset%2FMIMO%2FRaw%2DCSI%2DData). The number of antennas in the Argos dataset is 96, whereas `csidata.npy` contains data for only 8 antennas. Could you please advise on how to align the data shapes?
Thank you for your time and assistance.

**Comment by XPengZhao** [comment]
We follow the experimental setup described in FIRE [1]. The authors detail in Section 6.2 that "We trained FIRE on the Argos dataset with an 8-antenna base station and a client at different locations." Consequently, we utilize the direct slice of data provided by Argos. The CSI is extracted using IrisUtils [2]. Considering the data shape is `[:, 8, 96]`, we perform slicing with `[:, 0, :8]`.

[1] FIRE: Enabling Reciprocity for FDD MIMO Systems
[2] https://github.com/renew-wireless/RENEWLab/tree/master/PYTHON/IrisUtils

**Comment by Spinning-Fish** [comment]
Thanks for your help!

**Comment by xuanyv** [comment]
I would like to know how to obtain CSI using IrisUtils, specifically how to use the samps2csi function, as I am confused about where to obtain some of its parameters. Looking forward to your response. Thank you!

**Comment by whitecloudy** [comment]
For those who wonder, "csidata.npy" came from "ArgosCSI-96x8-2016-11-04-05-37-37_2.4GHz_track_left_to_right_NLOS.npy" with [0:4000, 1, :8].
