### ISSUE TITLE
Codes for Fig.2

### ISSUE THREAD

**Issue by Liu-Zhilin** [XPengZhao/NeRF2#9]
Thanks for sharing the codes. Your team's project is quite inpressive and appealing!
I'm trying to reproduct the spatial spectrums generated by NeRF2 and ground truth. Could you please show more codes for Fig.2?
Thank you for your time and assistance.

**Comment by XPengZhao** [comment]
The drawing code you're looking for can be found in `utils/data_painter.py`. If you're aiming to generate spatial spectrums from the phase values of the antenna array, you can utilize a conventional beamforming algorithm. For a practical example, please refer to `dataset_tools/gen_spectrum.py`.

**Comment by Liu-Zhilin** [comment]
Thank you for your help!

**Comment by iyi52** [comment]
Do you know how to apply this PCB file to MATLAB，I hope to reproduce ray tracing
